#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("roborally.Resource", IsApplication=true)]

namespace roborally
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int Orange = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int errorColor = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			public static int LarryPage {
				get;
				set;
			}

			public static int roboBackground {
				get;
				set;
			}

			
			// aapt resource value: 0x7f020000
			public const int achtergrond2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bgameinfo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bnewgame = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Bopties = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Bprofiel = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Btoeschouwer = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BVrienden = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int eyepatch = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int facebook = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int newgame = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int onlineaGame = 2130837516;

			// aapt resource value: 0x7f02000d
			public const int robotmenu = 2130837517;
			
			// aapt resource value: 0x7f02000d
			public const int robot = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int robotmenu = 2130837519;
			
			// aapt resource value: 0x7f02000g
			public const int singleplayer = 2130837520;

			// aapt resource value: 0x7f02000h
			public const int LarryPage = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int button1 = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int button2 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int button3 = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int editText1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int editText2 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int imageButton1 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int imageButton2 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int imageButton3 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int imageButton4 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageButton5 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int imageButton6 = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int imageView2 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int mainlayout = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GameInfo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Menu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NieuwSpelMenu = 2130903043;

			// aapt resource value: 0x7f030004
			public const int profiel = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
